# Generated by Django 3.1.7 on 2021-09-20 17:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_entities', '0003_auto_20210920_1741'),
    ]

    operations = [
        migrations.AddField(
            model_name='pokemonentity',
            name='Pokemon',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='pokemon_entities.pokemon'),
        ),
    ]
